//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDownloader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("siteName=猫咪AV\tdomain=https://www.ttt311.com/\timgType=piclist3\timgKeys=\tpageRegex=" +
            "<li><a\\b[^<>]*?\\bhref[\\s\\t\\r\\n]*=[\\s\\t\\r\\n]*[\"\']?[\\s\\t\\r\\n]*(?<matchStr>[^\\s\\t\\r" +
            "\\n\"\'<>]*)[^<>]*?[\\s\\t\\r\\n]*target=\"_blank\"\turlPattern=<domain>htm/<imgType>/<pag" +
            "eIndex>.htm\tfirstPageUrlPattern=\r\nsiteName=千百撸\tdomain=https://333av.vip/\timgType" +
            "=oumei\timgKeys=\tpageRegex=<li><a\\b[^<>]*?\\bhref[\\s\\t\\r\\n]*=[\\s\\t\\r\\n]*[\"\']?[\\s\\t" +
            "\\r\\n]*(?<matchStr>[^\\s\\t\\r\\n\"\'<>]*)[^<>]*?[\\s\\t\\r\\n]*target=\"_blank\"\turlPattern=" +
            "<domain>html/tupian/<imgType>/index_<pageIndex>.html\tfirstPageUrlPattern=<domain" +
            ">html/tupian/<imgType>/index.html\r\nsiteName=五月香\tdomain=http://www.dazhuazhi.com/" +
            "\timgType=1-1-4-68\timgKeys=\tpageRegex=<a\\b[^<>]*?\\bhref[\\s\\t\\r\\n]*=[\\s\\t\\r\\n]*[\"\'" +
            "]?[\\s\\t\\r\\n]*(?<matchStr>[^\\s\\t\\r\\n\"\'<>]*)[^<>]*?[\\s\\t\\r\\n]*target=\"_blank\" alt=" +
            "\"\turlPattern=<domain>lm/<imgType>-<pageIndex>.html\tfirstPageUrlPattern=\r\nsiteNam" +
            "e=2017MN\tdomain=http://www.2017mn.com/\timgType=oumei\timgKeys=\tpageRegex=<li><a\\b" +
            "[^<>]*?\\bhref[\\s\\t\\r\\n]*=[\\s\\t\\r\\n]*[\"\']?[\\s\\t\\r\\n]*(?<matchStr>[^\\s\\t\\r\\n\"\'<>]*" +
            ")[^<>]*?[\\s\\t\\r\\n]*target=\"_blank\"><span>\turlPattern=<domain>tupianqu/<imgType>/" +
            "index_<pageindex>.html\tfirstPageUrlPattern=<domain>tupianqu/<imgType>/index.html" +
            "\r\nsiteName=桃花族\tdomain=http://thzvv.com/\timgType=221\timgKeys=id=\tpageRegex=<a\\b[^" +
            "<>]*?\\bhref[\\s\\t\\r\\n]*=[\\s\\t\\r\\n]*[\"\']?[\\s\\t\\r\\n]*(?<matchStr>[^\\s\\t\\r\\n\"\'<>]*)[" +
            "^<>]*?[\\s\\t\\r\\n]*onclick=\"atarget\turlPattern=<domain>forum-<imgType>-<pageIndex>" +
            ".html\tfirstPageUrlPattern=\r\nsiteName=超碰\tdomain=https://2020.baofee.com/\timgType=" +
            "0\timgKeys=id=\"album_photo\tpageRegex=<div class=\"album_box_new\">[\\s\\t\\r\\n]*<a\\b[^" +
            "<>]*?\\bhref[\\s\\t\\r\\n]*=[\\s\\t\\r\\n]*[\"\']?[\\s\\t\\r\\n]*(?<matchStr>[^\\s\\t\\r\\n\"\'<>]*)[" +
            "^<>]*?[\\s\\t\\r\\n]*>\turlPattern=<domain>albums?c=<imgType>&page=<pageIndex>\tfirstP" +
            "ageUrlPattern=\r\nsiteName=性吧\tdomain=http://sohu58bbs.net/\timgType=150\timgKeys=id=" +
            "\"aimg_\tpageRegex=<a\\b[^<>]*?\\bhref[\\s\\t\\r\\n]*=[\\s\\t\\r\\n]*[\"\']?[\\s\\t\\r\\n]*(?<matc" +
            "hStr>[^\\s\\t\\r\\n\"\'<>]*)[^<>]*?[\\s\\t\\r\\n]*\turlPattern=<domain>forum-<imgType>-<pag" +
            "eIndex>.html\tfirstPageUrlPattern=\r\n")]
        public string webInfo {
            get {
                return ((string)(this["webInfo"]));
            }
            set {
                this["webInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"siteName\":\"猫咪AV\",\"domain\":\"https://www.jj796.com/\",\"imgType\":\"girllist10\",\"web" +
            "siteConverter\":null,\"imgKeys\":[\"\"],\"pageRegex\":\"<li><a\\\\b[^<>]*?\\\\bhref=[\\\"\']?(?" +
            "<matchStr>[^\\\"\'<>]*)[^<>]*?target=\\\"_blank\\\"\",\"urlPattern\":\"<domain>htm/<imgType" +
            ">/<pageIndex>.htm\",\"firstPageUrlPattern\":\"\"},{\"siteName\":\"千百撸\",\"domain\":\"https:/" +
            "/333av.vip/\",\"imgType\":\"oumei\",\"websiteConverter\":null,\"imgKeys\":[\"\"],\"pageRegex" +
            "\":\"<li><a\\\\b[^<>]*?\\\\bhref=[\\\"\']?(?<matchStr>[^\\\"\'<>]*)[^<>]*?target=\\\"_blank\\\"\"" +
            ",\"urlPattern\":\"<domain>html/tupian/<imgType>/index_<pageIndex>.html\",\"firstPageU" +
            "rlPattern\":\"<domain>html/tupian/<imgType>/index.html\"},{\"siteName\":\"五月香\",\"domain" +
            "\":\"http://www.dazhuazhi.com/\",\"imgType\":\"1-1-2-63\",\"websiteConverter\":null,\"imgK" +
            "eys\":[\"\"],\"pageRegex\":\"<a\\\\b[^<>]*?\\\\bhref=[\\\"\']?(?<matchStr>[^\\\"\'<>]*)[^<>]*?ta" +
            "rget=\\\"_blank\\\" alt=\\\"\",\"urlPattern\":\"<domain>lm/<imgType>-<pageIndex>.html?tu=2" +
            "\",\"firstPageUrlPattern\":\"\"},{\"siteName\":\"2017MN\",\"domain\":\"http://www.2017mn.com" +
            "/\",\"imgType\":\"oumei\",\"websiteConverter\":null,\"imgKeys\":[\"\"],\"pageRegex\":\"<li><a\\" +
            "\\b[^<>]*?\\\\bhref=[\\\"\']?(?<matchStr>[^\\\"\'<>]*)[^<>]*?target=\\\"_blank\\\"><span>\",\"u" +
            "rlPattern\":\"<domain>tupianqu/<imgType>/index_<pageindex>.html\",\"firstPageUrlPatt" +
            "ern\":\"<domain>tupianqu/<imgType>/index.html\"},{\"siteName\":\"桃花族\",\"domain\":\"http:/" +
            "/thzvv.com/\",\"imgType\":\"221\",\"websiteConverter\":null,\"imgKeys\":[\"id=\"],\"pageRege" +
            "x\":\"<a\\\\b[^<>]*?\\\\bhref=[\\\"\']?(?<matchStr>[^\\\"\'<>]*)[^<>]*?onclick=\\\"atarget\",\"u" +
            "rlPattern\":\"<domain>forum-<imgType>-<pageIndex>.html\",\"firstPageUrlPattern\":\"\"}," +
            "{\"siteName\":\"超碰\",\"domain\":\"https://2020.baofee.com/\",\"imgType\":\"0\",\"websiteConve" +
            "rter\":null,\"imgKeys\":[\"id=\\\"album_photo\"],\"pageRegex\":\"<div class=\\\"album_box_ne" +
            "w\\\"><a\\\\b[^<>]*?\\\\bhref=[\\\"\']?(?<matchStr>[^\\\"\'<>]*)[^<>]*?>\",\"urlPattern\":\"<dom" +
            "ain>albums?c=<imgType>&page=<pageIndex>\",\"firstPageUrlPattern\":\"\"},{\"siteName\":\"" +
            "性吧\",\"domain\":\"http://sohu58bbs.net/\",\"imgType\":\"150\",\"websiteConverter\":null,\"im" +
            "gKeys\":[\"id=\\\"aimg_\"],\"pageRegex\":\"<a\\\\b[^<>]*?\\\\bhref=[\\\"\']?(?<matchStr>[^\\\"\'<>" +
            "]*)[^<>]*?\",\"urlPattern\":\"<domain>forum-<imgType>-<pageIndex>.html\",\"firstPageUr" +
            "lPattern\":\"\"}]")]
        public string myWebsites {
            get {
                return ((string)(this["myWebsites"]));
            }
            set {
                this["myWebsites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int customItem {
            get {
                return ((int)(this["customItem"]));
            }
            set {
                this["customItem"] = value;
            }
        }
    }
}
